### ISSUE TITLE
Can't support sock5

### ISSUE THREAD

**Issue by xueqingsun** [lc4t/tumblr_download#1]
My sock5 is local shadowsocks, and the SS is used by me in daily work.
the tumblr_download can't support sock5 hosted by SS.
Would you have a look at the issue?

D:\GreenApplications\tumblr_download-master>python tumblr.py -s bjsxey  --type=both --thread=10  --proxy=sock5://127.0.0.1:1199
[2017-01-10 20:13:40.749410] [WinError 183] Cannot create a file when that file already exists: 'bjsxey'
Traceback (most recent call last):
  File "tumblr.py", line 177, in <module>
    tasks(site, options.type, int(options.thread))
  File "tumblr.py", line 148, in tasks
    total = crawler(site, types)
  File "tumblr.py", line 128, in crawler
    if requests.get('http://%s.tumblr.com/' % (site), proxies=PROXY).status_code != 200:
  File "D:\Users\ag\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Users\ag\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Users\ag\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Users\ag\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "D:\Users\ag\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "D:\Users\ag\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 290, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "D:\Users\ag\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 194, in proxy_manager_for
    **proxy_kwargs)
  File "D:\Users\ag\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\poolmanager.py", line 363, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "D:\Users\ag\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\poolmanager.py", line 314, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
requests.packages.urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme sock5

**Comment by lc4t** [comment]
Sorry for that.
Maybe you have a typo, **sock5**->**socks5**
see the help message:
**--proxy=PROXY         socks5://127.0.0.1:1080**

Others, I forgot to write `requirements.txt`

Test in MacOS, Python3.6

**Comment by xueqingsun** [comment]
Many thanks! It worked.
I'm using Windows 10.
